language: bash
sudo: required
dist: trusty
script: sudo make
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq debootstrap xz-utils qemu-user-static make -y
before_deploy:
- chmod -R 777 dist
deploy:
  provider: releases
  api_key:
    secure: S7nSrk1Xntg8PJWUB3nDfuABaAVsUPHacN6DveYapPXc+tG3HnQKLVQsBuRBPMxb+EzqUSZpsTsrZ6qWR0pUeTZTtbyBtLEO4tEm7b6NQfryLuZxLjYuv2nLZv/PJp6ehgObXiKkJS+tn5WeDGps+9frMqMBOsqSv5lqezck1b7aif4b121WgP/A9mCdUgCUSNm75hZhW98mnY1erc+t/7mubzoP13mw8JfDT2PTLwmanI+GRdjRIT7HoeQcLi+KXTqL0Zejz3WJ4sFrkO3IRhtioGaPEhfUlgUtD5Ci/Dbp4ElNwW+aqzLhzMZgtp2FcTv4jMKbhwBfYY+laFuApsUVWB6BK8tK+BnuCQUlBaGWt4xrc2Hf0FWjhHebiJcL/txoYbsSQyhIIL1N0nLljx4rOLNzh1WQTfEJD8A0zoG3xOY7bJ2/281/aTfxBQhB6SKwxKzDPYZWAVovWYcW48nW1ok+/d0qLuj01D8K837bR5R3bFHn82TjqHD6HO9B63zGn2W+QyeAUhj/qGgKA+GsQg9E/Xs6XLZojZleWKlnyx2LAwFNeyeKOk/73EL2W6oluNo+EKaX7RfDOZOcmkRDs4p4Fzpd4IzTsz5GMMoKWT7Hwog5M060AnMluAHouLnRRlnHT7ACk69mPNE+d0151ioYNnLaGIAGRZ4H9og=
  file:
    - dist/pmsbox-odroidc1_1.0.0.img.xz
    - dist/pmsbox-suite-odroidc1_1.0.0.img.xz
  skip_cleanup: true
  on:
    repo: tproenca/pmsbox
    branch: travis
    tags: true
